services:
  db_node_api_ts:
    image: mysql:latest
    container_name: db_node_api_ts
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: node_api_ts
      MYSQL_USER: user_reyes
      MYSQL_PASSWORD: h0l4_2025
      MYSQL_ROOT_PASSWORD: r00t_2025
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    external: true
